[workspace]
members = [
  "boards/adafruit_nrf52pro",
  "boards/adafruit-nrf52-bluefruit-le",
  "boards/nRF52-DK",
  "boards/nRF52840-DK",
  "boards/nRF9160-DK",
  "boards/actinius-icarus",
  "nrf52810-hal",
  "nrf52832-hal",
  "nrf52840-hal",
  "nrf5340-app-hal",
  "nrf5340-net-hal",
  "nrf9160-hal",
  "examples/rtfm-demo",
  "examples/spi-demo",
  "examples/twi-ssd1306",
]

[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = false

[profile.release]
debug = true
lto = true
opt-level = "s"


[patch.crates-io]
nrf52810-pac = { git = "https://github.com/JJJollyjim/nrf52810-pac.git" }
nrf52832-pac = { git = "https://github.com/nrf-rs/nrf52832-pac.git" }
nrf52840-pac = { git = "https://github.com/JJJollyjim/nrf52840-pac.git" }
nrf91 = { git = "https://github.com/JJJollyjim/nrf91-rs.git" }
